name: flutter_boiler_plate
description: A flutter boiler plate code for faster development time

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ##utils
  rxdart: ^0.24.1
  provider: ^4.1.2
  get_it: ^4.0.2
  easy_localization: ^2.3.2
  firebase_core: ^0.4.5
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.7+3
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  ##UI
  cupertino_icons: ^0.1.3
  toast: ^0.1.5
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.8.1
  material_design_icons_flutter: ^4.0.5345
  jin_widget_helper: ^1.3.2

  ##network
  dio_http_cache: ^0.2.6
  dio: ^3.0.9

dev_dependencies:
  hive_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - resources/language/en-US.json
    - resources/language/km-KH.json

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
